### ISSUE TITLE
Xoutput crashing all the time

### ISSUE THREAD

**Issue by stryxz** [csutorasa/XOutput#104]
i have all requiriments
-windows 10 updated to 1803
-all vc redists
-Vigem 
-Scp toolkit

Even so i always get that

![Screenshot_1](https://user-images.githubusercontent.com/53075646/61516827-29c22780-a9dc-11e9-80a6-60734c6c37b0.png)
![Screenshot_2](https://user-images.githubusercontent.com/53075646/61516829-29c22780-a9dc-11e9-8e1d-93cef7feef5e.png)

**Comment by ardor97** [comment]
@stryxz It's strange. XOutput writes in Output that ViGem is not installed. Maybe this crash is caused by simultaneous installed ViGem and SCPToolkit? Please, send the log. It will be useful for @csutorasa. I hope, he could help you to solve this problem.
I have a latest verison of XOutput and ViGem & HidGuardian installed. Eveything works perfectly for my crappy and cheap Oklick GP310m gamepad.

**Comment by DuckerMan** [comment]
May be, you should re-install Vigem?
