### ISSUE TITLE
Continuous Lagging

### ISSUE THREAD

**Issue by Tiefseetauchner** [csutorasa/XOutput#108]
I get the window, and after about a minute, I can click something, then I have to wait again, hence and repeat. Also, when changing my wheel axis on my g29, It lags. Same with every other button.
I think to have installed all dependencies listed. 

My system (maybe it helps):
CPU:
	Intel(R) Core(TM) i7-4800MQ CPU @ 2.70GHz
RAM:
	20,0 GB DDR3
GPU 0:
	Intel(R) HD Graphics 4600
	Driver version:	20.19.15.5058
	Driver date:	16/08/2018
	DirectX version:	12 (FL 11.1)
GPU 1:
	NVIDIA Quadro K2100M
	Driver version:	25.21.14.2551
	Driver date:	01/05/2019
	DirectX version:	12 (FL 11.0)

(I don't think, I'm underpowered...)

**Comment by csutorasa** [comment]
Can you tell me which version you are using, and send me a log file?

**Comment by Tiefseetauchner** [comment]
I tried multiple versions, all had the same problem. Rn, I think I'm "using" 3.19.1.
 I didn't think about the log file, sorry.
[XOutput.log](https://github.com/csutorasa/XOutput/files/3428067/XOutput.log)

**Comment by csutorasa** [comment]
You have a few really strange devices (some of them has 1000+ buttons). The problem is that you have 2 devices which cannot be read from, and a huge amount of errors are handled, causing the lagging.

I think the root cause is that the application keeps trying to read from devices that are failed to read from. I am thinking of a way where I could just safely disconnect these devices.

**Comment by csutorasa** [comment]
Please test the 3.21 version

**Comment by Tiefseetauchner** [comment]
It seems to work now, thanks!
