### ISSUE TITLE
Error compiling, missing Nefarius.ViGEm.Client

### ISSUE THREAD

**Issue by onimac92** [csutorasa/XOutput#143]
I have an error while trying to compile XOutput in Microsoft Visual Studio Community 2019 Version 16.4.2, it says it cannot find the package "Nefarius.ViGEm.Client".

I enclose an image to illustrate the error, I am sorry that it is in Spanish (I am Spanish-speaking).

![image](https://user-images.githubusercontent.com/37885126/71655008-2f51c680-2d0b-11ea-82b1-ca55028167ce.png)

This is the message in Spanish:
Error NU1101: No se encuentra el paquete Nefarius.ViGEm.Client. No existe ningún paquete con este id. en los orígenes: Microsoft Visual Studio Offline Packages, nuget.org

English (Google Translator)
Error NU1101: The Nefarius.ViGEm.Client package is not found. There is no package with this id. at the origins: Microsoft Visual Studio Offline Packages, nuget.org

**Comment by csutorasa** [comment]
This is because the ViGEm client version that I am using is not stable (yet). You either need to:
- Use Visual Studio to add a new package source with the url `https://ci.appveyor.com/nuget/vigem-net-ci`
- Use .NET core `dotnet.exe` and run `dotnet add XOutput package Nefarius.ViGEm.Client -s https://ci.appveyor.com/nuget/vigem-net-ci -v 1.16.138` in the root directory of the application.
When the ViGEm client will be final, I will switch to the new version.

**Comment by onimac92** [comment]
I already managed to build, thanks!
