### ISSUE TITLE
Two Gamepads with same ID

### ISSUE THREAD

**Issue by Luxumbra27** [csutorasa/XOutput#159]
Hello @csutorasa ! 
First **thank you very much** for this amazing project ! It saved me after spending countless hours on various softwares, yours is the best ! 

I have an issue that may be related to #130 :
Two of my gamepads have the same name/id, the one in the parenthesis:
"InputDevice": "95524a20-6ae3-11ea-8002-444553540000".

![Capture1](https://user-images.githubusercontent.com/17299920/77246305-2dbadf00-6c26-11ea-91d2-10e55fb1e3f9.PNG)
![Capture2](https://user-images.githubusercontent.com/17299920/77246308-30b5cf80-6c26-11ea-9fc1-5d943e4a476e.PNG)

I have manually edited the settings.json file so the mapping is good for both devices, but when they are both plugged in, I only one of the two has its output received by Xoutput, and is sent to both of the game controllers configured.

Here is the relevant extract from the settings file:
```
"StartWhenConnected": false,
      "Name": "ControllerBlack",
      "Id": "972ed9c5-9d3e-4e54-af2d-940242436e69",
      "ForceFeedbackDevice": null,
      "Mappings": {
        "A": {
          "Mappers": [
            {
              "InputDevice": "db52c7d0-6ae2-11ea-8001-444553540000",
		  
"StartWhenConnected": false,
      "Name": "ControllerBlue",
      "Id": "16d777fd-09a9-44bd-bbb5-c1e00f211b88",
      "ForceFeedbackDevice": null,
      "Mappings": {
        "A": {
          "Mappers": [
            {
              "InputDevice": "db52c7d0-6ae2-11ea-8001-444553540000",
```

Tell me if you have a quick workaround for now, and if you need any help testing, I have a bit of knowledge.

Thks,

**Comment by sebsjara** [comment]
help I have the same problem

**Comment by csutorasa** [comment]
The ID is the `InstanceGuid`. It means it identifies the instance (device), and is a globally unique identifier. So there should not be two devices with the same ID on one Windows installation, that is why the software is not ready for that. Sadly I do not know any quick workaround.

**Comment by Luxumbra27** [comment]
Solved the issue ! Thank you for the quick information @csutorasa !

The problem seems to be on the Windows side. Windows seems to do some kind of calculation when the devices drivers are installed based on the device details in order to get a "unique" `InstanceGuid`...
I found out that once it is calculated, the devices sticks to it, _unless it is reinstalled_. We need to change that `InstanceGuid" for at least one device, so let's _reinstall it_.
Here is what I did (maybe @csutorasa will tell us which steps are useless):

1. Remove one of the devices
2. Go to `Devices and printers` -> right click on the device still plugged in -> Properties
3. In the second tab, **for each** `Device functionalities`: Properties -> Change settings -> Driver -> Uninstall device
4. Unplug the device
5. Plug back in the **other** device
6. Plug back in the device that was uninstalled

You should have a new `InstanceGuid`, different from the other one !
Tell me if it works for you, it did for me !

Cheers,
Lux

**Comment by sebsjara** [comment]
HI, I still have the same problem, I explain the problem more deeply. I have four classic xbox controls with XBCD drivers, all four controls have the same VID: 0xFFFF and PID: 0xFFFF and the InstanceGuid is almost the same,

![image](https://user-images.githubusercontent.com/17729303/77488976-cdce5f00-6e04-11ea-8a9b-cb15e2073ec0.png)
here is only two controllers.


![image](https://user-images.githubusercontent.com/17729303/77489227-7e3c6300-6e05-11ea-9e85-6c34d692dcf1.png)


I did the procedure of @Luxumbra27 but still the same, when moving the analog stick or the triggers, all four controls it they turn green, it is not a real problem because at the time of playing a game the interference is not noticed, but it would be good if there were any solution in the future.

[settings - copia.json.txt](https://github.com/csutorasa/XOutput/files/4378408/settings.-.copia.json.txt)

[XOutput - copia.log.txt](https://github.com/csutorasa/XOutput/files/4378410/XOutput.-.copia.log.txt)

**Comment by Luxumbra27** [comment]
According to this extract from your settings:
![Capture](https://user-images.githubusercontent.com/17299920/77529782-93120880-6e90-11ea-9c37-089322069fd1.PNG)

There seems to be a mess in the `ForceFeedbackDevice` settings, try disabling it and , maybe it triggers the green, and there is no real issue.
The two controllers here don't have the same `InstanceGuid`, so al least you do not have the identical `InstanceGuid` issue I had.
