### ISSUE TITLE
Please fix saved configurations

### ISSUE THREAD

**Issue by kevinhua23** [csutorasa/XOutput#197]
I constantly have to re-map my configurations to my bluetooth controller everytime I disconnect and reconnect my controller.

It would be a great alternative if each time I connect a dinput controller via bluetooth to immediately associate it to the last saved xinput controller configuration.

**Comment by Jukiro** [comment]
I'm experiencing this issue too. Hoping for a fix.

**Comment by thiag0pc** [comment]
I was using the 3.22 version because this problem, but after I formatted the computer, it no longer recognizes the installed ViGem. From 3.23 onwards he recognizes normally, but then we have again this problem.

**Comment by OWL282820** [comment]
I'm having the same problem. But bindings drop shortly after starting XOutput. I would be really greatful for a fix as there's no exact alternave to XOutput. I cannot use standard gamepads for XInput games due to medical condition that leaves me with tremor. Using hotas-sized joysticks reduces this for me. I've been using XOutput for years and really hoping it's not dead. (XOutpu.log attached).

https://hastebin.com/etediyajev.yaml

**Comment by Zaanza** [comment]
- Set Read-only on settings.json properties after you configure your devices.
- Use "Restart On Crash" for XOutput crashes.

- Or test x360ce (equivalent software) but it kill HidGuardian (issue corrected maybe?), it will be necessary to add the device manually in the registry including to return to XOuput.

**Comment by OWL282820** [comment]
> 
> 
>     * Set Read-only on settings.json properties after you configure your devices.
> 
>     * Use "Restart On Crash" for XOutput crashes.
> 
>     * Or test x360ce (equivalent software) but it kill HidGuardian (issue corrected maybe?), it will be necessary to add the device manually in the registry including to return to XOuput.

Thanks for your suggestions Zaanza. I've already tried the first two, without success, and was reluctant to switch to x360ce, sinc I've been with xOutput for several years. But, since there doesn't seem to be a solution to the specific problem I have, I've switched to x360ce. And although it involves a bit mre hassle, I suppose I will have to stick to it.

Thanks again.

**Comment by Zaanza** [comment]
The first two solutions work 100% on the PCs where I install it.

**Comment by kevinhua23** [comment]
@Zaanza Can you show us step by step on how to do the first solution?

**Comment by Zaanza** [comment]
Sorry for bad english.
- Configure your controller in XOuput, disable run at startup in settings (and click on save settings for edit the settings.json).
- In XOutput installation folder, right click on settings.json → Properties → Check Read-only → OK (this will prevent any modification of the file even by the user).

- Download RestartOnCrash and extract folder in your programs.
- In RestartOnCrash settings check start at startup, minimized, system tray...
- Add XOutput in RestartOnCrash like this :
![Untitled](https://user-images.githubusercontent.com/53754105/98464628-81356980-21c4-11eb-9ee1-e393c013d9dc.png)

**Comment by kevinhua23** [comment]
Can I do the above solution without RestartOnCrash? Just the Set Read-only on settings.json properties

**Comment by Zaanza** [comment]
Yes, but sometimes the program closes on its own after launch games, I think that's what's bothering it.

**Comment by kevinhua23** [comment]
Tried the method and did not work for me.. When I went to disconnect my controller and reconnect it, the saved configurations became all blank again. :( Hope we get a fix soon..

**Comment by csutorasa** [comment]
Fix is released in 3.29.

**Comment by kevinhua23** [comment]
@csutorasa You're a godsend. works flawlessly now! Thanks a bunch
