### ISSUE TITLE
Hide real DInput device from games

### ISSUE THREAD

**Issue by ardor97** [csutorasa/XOutput#28]
I've tested vibration yesterday. It works perfectly for my cheap and crappy gamepad OKLICK GP-310M (tested games: Castlevania LoS 2, Sonic All-Stars Racing, Wonderboy The Dragon's Trap). 
Is it possible to hide real DirectInput device from game? Without hiding some games (for example FIFA, Mortal Kombat) try to detect gamepad via DirectInput, that's why all don't works correctly (double input).
I've read that hiding real device in such project as InputMapper (for DualShock 4) is realised via ViGEm HidGuardian and HidCerberus,Srv.

Many thanks for your titanic work!

**Comment by hik4ru** [comment]
Same request; somehow I used latest XOutput release to play Rocket League with Switch's Pro Controller and suddenly today it catches this kinda double controller — Xinput as configured and DirectInput too.

Thank you very much for your effort and fast development, though.

**Comment by csutorasa** [comment]
I could make contact with @nefarius. A new release of HidGuardian and HidCerberus are coming soon. I will help him to test and I hope it will work with my application.
Sadly, I cannot promise any ETA on this issue.

**Comment by fabrebatalla18** [comment]
I need the same, please.

**Comment by mkultimate** [comment]
in the games of LEGO the same thing causes a problem since when pressing a button in directInput the same happens with the XInput at the same time :(

**Comment by toolschmiede** [comment]
As XOutput works perfectly I am also looking forward to see a solution to dinput blocking. I can't get HidGuardian run. So I'll wait and hope you'll look further into this great feature request! 👍

**Comment by H8to** [comment]
Does anyone have a workaround and can describe here how to hide the dinput?

There are some games that act strange when they see both inputs. (E.g. Disabling xinput, which cripples the support for additional controllers with native xinput)

@csutorasa Did you try HidGuardian? I'm not able to get it working.

**Comment by Tyall** [comment]
I tried to block dinput by adding my controller (Logitech Dual Action) to the HidGuardian in regedit. After that Xoutput doesn't see my controller even though it's listed in both Device Manager and Devices and Printers. Strange thing. Would appreciate any help cuz i'm trying to get it to work with a new Forza game.

**Comment by csutorasa** [comment]
I could not make it work yet, I am still planning to include this in future versions, but I do not think it is stable enough. Test versions are available and you may try to discord channel of @nefarius at his [homepage](https://vigem.org/).

If I am not wrong if you add the configuration to regedit, it will block all applications. You will need to use another configuration (registry) to set which applications may use the device. I still recommend the discord channel for further info.

**Comment by Tyall** [comment]
> If I am not wrong if you add the configuration to regedit, it will block all applications. You will need to use another configuration (registry) to set which applications may use the device. I still recommend the discord channel for further info.

After whitelisting Xoutput for HIDGuardian/Cerberus it works perfectly in forza horizon4  demo! Thanks for help! <3

**Comment by csutorasa** [comment]
I am happy to hear that. Could you comment the replication steps? It may be useful for others, until I can integrate with HIDGuardian.

**Comment by Tyall** [comment]
I will try my best but it might be unclear since i'm a noob.
So thats what i did:
1. Download and setup Xoutput + ViGEm
2. Download HIDGuardian and install it
3. Find out your Contoller's hardware ID. You can do it this way: Control Panel -> Devices and Printers -> Right click your controller -> Properties ->Hardware -> Now select the option with HID in its name ->Properties -> Details -> Hardware IDs -> Copy 3 first lines. It should look somehow like this:
HID\VID_046D&PID_C216&REV_0300
HID\VID_046D&PID_C216
HID\VID_046D&UP:0001_U:0004
4. Now go open regedit, navigate to HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\HidGuardian\Parameters
and add these 3 lines to the Affected devices and restart your PC
5. Here's the part with whitelisting Xoutput. I'm not sure how to do it by coding but i found a simple application called WhiteKnight Auto Whitelister (i'm not sure i can post links here so i won't)
6. Download the app and run it as administrator. From here you can also install HidCerberus or HidGuardian so my "guide" can be a bit simpler. Click "Pick App" and focus window with Xoutput to whitelist it. 
7. As i mentioned i'm not sure how it worked but i restarted my pc here. Checked again - my controller was hidden for everything except Xoutput so i started emulation and tested if it works ingame. Worked perfectly!
Hope it was at least a bit helpful. Thanks for desigining this amazing app @csutorasa

**Comment by nefarius** [comment]
WhiteKnight is a GUI tool by one of our developers. It adjusts the whitelisting registry keys at runtime.

**Disclaimer:** I do not recommend you program against this interface because it's outdated and requires elevated privileges.

If for example the key `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\HidGuardian\Parameters\Whitelist\1234` exists, the process running under PID `1234` will get whitelisted by the driver. So what WK does is to map the process name to the PID and creates/deletes these keys accordingly. This is tedious and error-prone but that's how it's done in HG Gen1.

**Comment by LLltirlec** [comment]
@csutorasa XOutput does not work in this game due to the fact that the function of hiding the gamepad is not implemented.
You need:

Add HIDGuardian install / uninstall buttons
Add the checkbox "Hide gamepad" and the window with the message: "Reconnect gamepad"
Data is written to the Windows registry "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\HidGuardian\Parameters" in AffectedDevices, for example: "HID\VID_0810&PID_0001&COL01" or "HID\VID_044F&PID_B609"
Add a function so that the program itself adds itself to the white list at startup and deleted after closing. White list here "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\HidGuardian\Parameters\Whitelist"
Adding to the white list is done by creating a subsection with the process number in the section title in whitelist

**Comment by Darthagnon** [comment]
@csutorasa , Ryochan7 recently dropped HidGuardian from his DS4Windows project (it emulates an XInput controller with a DS4); I believe he now uses some sort of alternative system to hide the DS4 as an input. Maybe a similar approach could work for XOutput, to hide the DInput controllers from games? I've contacted him, will post back here if I get a reply RE: what exactly the hiding system he uses is.

**Comment by Darthagnon** [comment]
Ryochan7's reply:
https://github.com/Ryochan7/DS4Windows/issues/502#issuecomment-443531827
He uses a Windows Exclusive Mode workaround - guess it bypasses Windows drivers and talks directly to the program. InputMapper (similar to DS4Windows) has a post on their website with a bit more info on implementing exclusive mode (https://inputmapper.com/20-windows-10-1607-au-exclusive-mode-fix)

**Comment by csutorasa** [comment]
Added to v3.16

**Comment by ngxson** [comment]
@csutorasa This issue still happens to me. I'm using XOutput 3.26 with `PS3/PC Gamepad eb0c5340-3864-11ea-8002-444553540000` chinese controller.

**Comment by hifihedgehog** [comment]
HidHide will be adding this functionality soon. Was informed that HidGuardian is EOL-ed and HidHide is perhaps days away from its first public release. See [here](https://forums.vigem.org/topic/513/cannot-truly-hide-x360-controller-from-apps/4) and [here](https://github.com/ViGEm/HidGuardian/issues/7) for ViGEm team's @nefarius's posts alluding to an imminent release. HidHide will be replacing HidGuardian and--most notably--will be adding support for hiding XInput controllers.
