### ISSUE TITLE
XOutput not work on forza horizon 4 !

### ISSUE THREAD

**Issue by caioans** [csutorasa/XOutput#68]
https://www.youtube.com/watch?v=kL3rBJtm5j8

Does anyone have any solutions to play with generic control?

**Comment by csutorasa** [comment]
What device are you using? I see some flashing keyboard and gamepad icons in the game.

**Comment by caioans** [comment]
a copy of the xbox 360 controller, exactly this seems to be a conflict with the keyboard and mouse in the game. Output has always worked well with other games, but the icons blink and the control does not match well.

**Comment by LordVanHell** [comment]
> 
> 
> a copy of the xbox 360 controller, exactly this seems to be a conflict with the keyboard and mouse in the game. Output has always worked well with other games, but the icons blink and the control does not match well.

bro hello test Xoutput 3.13 and disconnect your mouse and keyboard, test again Should work, and again test 3.14 Tell me how it's going

**Comment by caioans** [comment]
I really do not know what it is, I've used all the entries on my pc, I've disconnected my keyboard and mouse, I've used another control and it still continues the same problem; It's only with Forza that, I'm very unlucky. Feels bad LUL

**Comment by LordVanHell** [comment]
> 
> 
> I really do not know what it is, I've used all the entries on my pc, I've disconnected my keyboard and mouse, I've used another control and it still continues the same problem; It's only with Forza that, I'm very unlucky. Feels bad LUL

try to change the crack of the game or install all updates the same

**Comment by LordVanHell** [comment]
> 
> 
> > I really do not know what it is, I've used all the entries on my pc, I've disconnected my keyboard and mouse, I've used another control and it still continues the same problem; It's only with Forza that, I'm very unlucky. Feels bad LUL
> 
> try to change the crack of the game or install all updates the same

sometimes it happens that the same crack blocks the configuration of controls

**Comment by LordVanHell** [comment]
> 
> 
> I really do not know what it is, I've used all the entries on my pc, I've disconnected my keyboard and mouse, I've used another control and it still continues the same problem; It's only with Forza that, I'm very unlucky. Feels bad LUL

    try to change the crack of the game or install all updates the same

sometimes it happens that the same crack blocks the configuration of controls

**Comment by xhbarbosa** [comment]
im having the exact same problem, the game has no crack yet

**Comment by LLltirlec** [comment]
@csutorasa XOutput does not work in this game due to the fact that the function of hiding the gamepad is not implemented.
You need:
1. Add HIDGuardian install / uninstall buttons
2. Add the checkbox "Hide gamepad" and the window with the message: "Reconnect gamepad"
Data is written to the Windows registry (HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\HidGuardian\Parameters) in AffectedDevices
3. Add a function so that the program itself adds itself to the white list at startup and deleted after closing. White list here (HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\HidGuardian\Parameters\Whitelist)
Adding to the white list is done by creating a subsection with the process number in the section title in whitelist

**Comment by JihedMrouki** [comment]
@LLltirlec can you explain the steps in a video or something ! i didn't understand what to do exactly , please

**Comment by csutorasa** [comment]
Added to v3.16
